"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { submitRepositoryAnalysis } from "@/lib/storage";
import { ErrorToast } from "@/components/assessment/ErrorToast";

interface RepositoryAnalysisSubmissionProps {
  userEmail: string;
  promptContent: string;
}

export function RepositoryAnalysisSubmission({
  userEmail,
  promptContent,
}: RepositoryAnalysisSubmissionProps) {
  const router = useRouter();
  const [jsonInput, setJsonInput] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [successMessage, setSuccessMessage] = useState("");
  const [copyMessage, setCopyMessage] = useState("");
  const [copyError, setCopyError] = useState("");
  const [toastError, setToastError] = useState("");

  const handleCopyPrompt = async () => {
    setCopyMessage("");
    setCopyError("");

    if (!navigator.clipboard?.writeText) {
      setCopyError(
        "Clipboard is unavailable. Select the prompt manually and copy it.",
      );
      return;
    }

    try {
      await navigator.clipboard.writeText(promptContent);
      setCopyMessage("Prompt copied to clipboard.");
    } catch {
      setCopyError(
        "Prompt could not be copied. Select it manually and try again.",
      );
    }
  };

  const handleSubmit = async () => {
    setError("");
    setSuccessMessage("");
    setToastError("");

    if (!jsonInput.trim()) {
      setError("Please paste the analysis JSON output.");
      return;
    }

    setIsSubmitting(true);
    try {
      await submitRepositoryAnalysis(jsonInput);
      setSuccessMessage(
        "Analysis submitted successfully! Redirecting to dashboard...",
      );
      setJsonInput("");

      // Redirect to dashboard after a brief delay
      setTimeout(() => {
        router.push("/dashboard");
      }, 1000);
    } catch (err) {
      if (err instanceof Error) {
        setError(err.message);
        setToastError(err.message || "Failed to submit analysis.");
      } else {
        setToastError("Failed to submit analysis.");
      }
      console.error("Submission error:", err);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleReset = () => {
    setJsonInput("");
    setError("");
    setSuccessMessage("");
  };

  return (
    <article className="card form-card">
      <ErrorToast message={toastError} onClose={() => setToastError("")} />
      <header className="card-header">
        <div className="form-header-row">
          <h2>Repository Analysis</h2>
          <span className="email-badge">{userEmail}</span>
        </div>
        <p>
          Submit a repository analysis generated by the AI analysis
          prompt.
        </p>
        <p className="section-description">
          Privacy mode: only scores and category-level data are stored.
          Free-text findings and sensitive details are intentionally not
          persisted.
        </p>
      </header>

      <div className="form-content">
        <section className="analysis-section">
          <h3>Repository Analysis Prompt</h3>
          <p className="section-description">
            Open the prompt, copy it, and paste it into your AI assistant before
            returning here with the JSON output.
          </p>

          <details className="json-format-helper prompt-helper">
            <summary>Open Prompt</summary>
            <div className="prompt-helper-actions">
              <button
                type="button"
                className="button ghost"
                onClick={() => void handleCopyPrompt()}
              >
                Copy Prompt
              </button>
            </div>
            <textarea
              value={promptContent}
              readOnly
              className="json-textarea prompt-textarea"
              aria-label="Repository analysis prompt"
              rows={18}
            />
          </details>

          {copyError && (
            <p className="form-error" role="alert" aria-live="assertive">
              {copyError}
            </p>
          )}
          {copyMessage && (
            <p className="form-success" role="status" aria-live="polite">
              {copyMessage}
            </p>
          )}
        </section>

        <section className="analysis-section">
          <h3>Paste Analysis JSON</h3>
          <p className="section-description">
            Run the repository analysis prompt in your AI assistant of choice,
            then paste only the JSON output here.
          </p>

          <textarea
            value={jsonInput}
            onChange={(e) => setJsonInput(e.target.value)}
            placeholder={`Paste only the JSON output from the analysis prompt here...`}
            className="json-textarea"
            disabled={isSubmitting}
            rows={12}
          />

          <details className="json-format-helper">
            <summary>Expected JSON Format</summary>
            <pre>{`{
  "analysis": {
    "pillars": {
      "pillar-1-ideation": {
        "title": "Pillar 1 – Ideation & Requirements",
        "questions": [
          { "id": "p1-q1", "score": 2 },
          { "id": "p1-q2", "score": 2 },
          { "id": "p1-q3", "score": 2 }
        ],
        "pillar_score": 2
      },
      "pillar-2-design": {
        "title": "Pillar 2 – Design & Architecture",
        "questions": [
          { "id": "p2-q4", "score": 2 },
          { "id": "p2-q5", "score": 2 },
          { "id": "p2-q6", "score": 2 }
        ],
        "pillar_score": 2
      },
      "pillar-3-development": {
        "title": "Pillar 3 – Development Hygiene",
        "questions": [
          { "id": "p3-q7", "score": 2 },
          { "id": "p3-q8", "score": 2 },
          { "id": "p3-q9", "score": 2 }
        ],
        "pillar_score": 2
      },
      "pillar-4-quality": {
        "title": "Pillar 4 – Quality Engineering",
        "questions": [
          { "id": "p4-q10", "score": 2 },
          { "id": "p4-q11", "score": 2 },
          { "id": "p4-q12", "score": 2 }
        ],
        "pillar_score": 2
      },
      "pillar-5-operations": {
        "title": "Pillar 5 – Operations & Maintenance",
        "questions": [
          { "id": "p5-q13", "score": 2 },
          { "id": "p5-q14", "score": 2 }
        ],
        "pillar_score": 2
      }
    },
    "raw_score": 28,
    "score_level": "Optimized"
  }
}`}</pre>
          </details>
        </section>

        <div className="form-actions">
          <button
            type="button"
            onClick={handleReset}
            className="button ghost"
            disabled={isSubmitting}
          >
            Clear
          </button>

          <button
            type="button"
            onClick={handleSubmit}
            className="button solid"
            disabled={isSubmitting || !jsonInput.trim()}
          >
            {isSubmitting ? "Submitting…" : "Submit Analysis"}
          </button>
        </div>

        {error && (
          <p className="form-error" role="alert" aria-live="assertive">
            {error}
          </p>
        )}
        {successMessage && (
          <p className="form-success" role="status" aria-live="polite">
            {successMessage}
          </p>
        )}
      </div>
    </article>
  );
}
